/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentsClassIdRouteImport } from './routes/contents.$classId'
import { ServerRoute as ApiAddclassesServerRouteImport } from './routes/api/addclasses'
import { ServerRoute as ApiHelloSplatServerRouteImport } from './routes/api/hello.$'
import { ServerRoute as ApiContentsSplatServerRouteImport } from './routes/api/contents.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsClassIdRoute = ContentsClassIdRouteImport.update({
  id: '/contents/$classId',
  path: '/contents/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddclassesServerRoute = ApiAddclassesServerRouteImport.update({
  id: '/api/addclasses',
  path: '/api/addclasses',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiHelloSplatServerRoute = ApiHelloSplatServerRouteImport.update({
  id: '/api/hello/$',
  path: '/api/hello/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiContentsSplatServerRoute = ApiContentsSplatServerRouteImport.update({
  id: '/api/contents/$',
  path: '/api/contents/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/contents/$classId': typeof ContentsClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/contents/$classId': typeof ContentsClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/contents/$classId': typeof ContentsClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/contents/$classId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/contents/$classId'
  id: '__root__' | '/' | '/dashboard' | '/contents/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ContentsClassIdRoute: typeof ContentsClassIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api/addclasses': typeof ApiAddclassesServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/contents/$': typeof ApiContentsSplatServerRoute
  '/api/hello/$': typeof ApiHelloSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/addclasses': typeof ApiAddclassesServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/contents/$': typeof ApiContentsSplatServerRoute
  '/api/hello/$': typeof ApiHelloSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/addclasses': typeof ApiAddclassesServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/contents/$': typeof ApiContentsSplatServerRoute
  '/api/hello/$': typeof ApiHelloSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/addclasses'
    | '/api/auth/$'
    | '/api/contents/$'
    | '/api/hello/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/addclasses' | '/api/auth/$' | '/api/contents/$' | '/api/hello/$'
  id:
    | '__root__'
    | '/api/addclasses'
    | '/api/auth/$'
    | '/api/contents/$'
    | '/api/hello/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAddclassesServerRoute: typeof ApiAddclassesServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiContentsSplatServerRoute: typeof ApiContentsSplatServerRoute
  ApiHelloSplatServerRoute: typeof ApiHelloSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/$classId': {
      id: '/contents/$classId'
      path: '/contents/$classId'
      fullPath: '/contents/$classId'
      preLoaderRoute: typeof ContentsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/addclasses': {
      id: '/api/addclasses'
      path: '/api/addclasses'
      fullPath: '/api/addclasses'
      preLoaderRoute: typeof ApiAddclassesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/hello/$': {
      id: '/api/hello/$'
      path: '/api/hello/$'
      fullPath: '/api/hello/$'
      preLoaderRoute: typeof ApiHelloSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/contents/$': {
      id: '/api/contents/$'
      path: '/api/contents/$'
      fullPath: '/api/contents/$'
      preLoaderRoute: typeof ApiContentsSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ContentsClassIdRoute: ContentsClassIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAddclassesServerRoute: ApiAddclassesServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiContentsSplatServerRoute: ApiContentsSplatServerRoute,
  ApiHelloSplatServerRoute: ApiHelloSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
